baseURL = 'https://guackamollyapps.com'

title = 'Guackamolly Apps'
author = 'Guackamolly Apps'
copyright = 'Copyright © 2024, Guackamolly Apps.'
languageCode = 'en'
defaultContentLanguage = 'en'

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[params.author]
  name = "Guackamolly Apps"
  headline = "We make apps that bring joy!"
  image = "78486244.png"
  links = [
    { email = "mailto:guackamolly.apps@gmail.com" },
    { link = { href = "https://github.com/jpanther/lynx/blob/stable/README.md", text = "View the readme", icon = "github" } },
    { link = { href = "styles/", text = "All the link styles", target = "_self" } },
    { github = "https://github.com/jpanther/lynx" },
    { x = "https://x.com/jpanther" },
    { font-awesome = { href = "https://fontawesome.com/", text = "FontAwesome" } },
  ]

[markup.highlight]
  noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true

[module]
  [module.hugoVersion]
    extended = false
    min = "0.86.1"
