baseURL = 'https://guackamollyapps.com'

title = 'Guackamolly Apps'
author = 'Guackamolly Apps'
copyright = 'Copyright © 2024, Guackamolly Apps.'
languageCode = 'en'
defaultContentLanguage = 'en'

enableEmoji = true
disableKinds = ["taxonomy", "term"]
enableRobotsTXT = true

params.attribution = false
params.keywords = ['guackamolly apps', 'guackamolly', 'guackamollyapps', 'apps', 'app development', 'indie development']

[params.author]
  name = "Guackamolly Apps"
  headline = "We make apps that bring joy!"
  image = "78486244.png"
  links = [
    { email = "mailto:guackamolly.apps@gmail.com" },
    { link = { href = "https://guackamollyapps.com/send-to-pocketbook", text = "Send to PocketBook", icon = "link" } },
    { link = { href = "https://guackamollyapps.com/guess-the-programming-language", text = "Guess The Programming Language", icon = "link" } },
  ]

[markup.highlight]
  noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true

[module]
  [module.hugoVersion]
    extended = false
    min = "0.86.1"
